# Default values for hello-world
replicaCount: 1

image:
  # 👇 Your ECR image repo
  repository: 942010118414.dkr.ecr.us-east-2.amazonaws.com/app-repository
  tag: 
  pullPolicy: IfNotPresent

# 👇 Pull secret created from your ECR login
imagePullSecrets:
  - name: ecr-cred

service:
  # 👇 Ensure app is exposed publicly through AWS Load Balancer
  type: LoadBalancer
  # 👇 Port the container listens on
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# 👇 Probes fixed to reference numeric port (8080)
livenessProbe:
  httpGet:
    path: /
    port: 8080
readinessProbe:
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
