apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  # 👇 Pulls LoadBalancer from values.yaml
  type: {{ .Values.service.type }}
  ports:
    - name: http
      # 👇 Exposes port 80 externally via ALB
      port: 80
      # 👇 Routes to port 8080 inside your container
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
