name: GitOps Sync Only

on:
  push:
    branches: [ gitops ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify ArgoCD
        run: echo "GitOps branch updated — ArgoCD will detect and sync automatically."
